### ISSUE TITLE
Some Errors... 

### ISSUE THREAD

**Issue by choikhss** [ybkscht/EfficientPose#13]
After training, I get this error #399 during the evaluation phase. 

**_ValueError: Layer #399 (named "class_net/class-predict"), weight <tf.Variable 'class_net/class_net/class-predict/pointwise_kernel:0' shape=(1, 1, 64, 9) dtype=float32> has shape (1, 1, 64, 9), but the saved weight has shape (1, 1, 64, 810)_**

As far as I know, I knew I had to match the number of classes, but even if I match the num_classes of train.py and evaluate.py, it doesn't work. Please.

**Comment by ybkscht** [comment]
Hi choikhss,

Do you accidentally try to load the COCO weights instead of your own trained weights?
Because the class prediction layer shape of the saved weights has exactly the shape of the COCO weights (810).

Sincerely,
Yannick

**Comment by choikhss** [comment]
no. I am currently using the COCO Weight provided by the author.

If so, am I supposed to use my own trained weights?

Thank you

**Comment by choikhss** [comment]
I Solved!!
