### ISSUE TITLE
some error with training Linemod

### ISSUE THREAD

**Issue by peppa114** [ybkscht/EfficientPose#16]
Hi, I have some problems with training. The screenshots of the problem are as follows:
![Screenshot from 2021-04-26 13-56-14](https://user-images.githubusercontent.com/83171253/116035458-9c733300-a697-11eb-8860-75529b30dad8.png)
![Screenshot from 2021-04-26 13-56-32](https://user-images.githubusercontent.com/83171253/116035480-a5640480-a697-11eb-96ba-6f3298daba2a.png)
And Numpy version in my virtual environment is 1.20.0, I have tried many versions
Could you give me some advices? I look forword to your reply.Thanks.

**Comment by ybkscht** [comment]
Hi peppa114,

The error seems to be related to your numpy version. I installed numpy 1.20.0 and faced the same error message.
After going back to numpy version 1.18.5 everything works as expected again.

Sincerely,
Yannick

**Comment by peppa114** [comment]
Hi Yannick,
I have tried again with numpy version 1.18.5,there are some errors as follows:





I think there is something wrong with the configuration environment.Could you help me?
Yours sincerely,
Peppa
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ybkscht/EfficientPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ybkscht/EfficientPose] some error with training Linemod (#16)





 
Hi peppa114,
 
The error seems to be related to your numpy version. I installed numpy 1.20.0 and faced the same error message.
 After going back to numpy version 1.18.5 everything works as expected again.
 
Sincerely,
 Yannick

**Comment by ybkscht** [comment]
Maybe this is because you compiled compute_overlap using numpy 1.20.0 which is now incompatible with 1.18.5.
You can try to compile compute_overlap again with `python setup.py build_ext --inplace` (delete compute_overlap.c and compute_overlap.xxx.pyd in the utils folder first to make sure it is really compiled again).

Sincerely,
Yannick

**Comment by peppa114** [comment]
> Maybe this is because you compiled compute_overlap using numpy 1.20.0 which is now incompatible with 1.18.5.
> You can try to compile compute_overlap again with `python setup.py build_ext --inplace` (delete compute_overlap.c and compute_overlap.xxx.pyd in the utils folder first to make sure it is really compiled again).
> 
> Sincerely,
> Yannick

OK！ I got it. Thanks very much!
