### ISSUE TITLE
NotImplementedError bug documentation

### ISSUE THREAD

**Issue by bainro** [ybkscht/EfficientPose#17]
I was getting the following error on Ubuntu 18.04:

```NotImplementedError: Cannot convert a symbolic Tensor (filtered_detections/map/while/strided_slice_1:0) to a numpy array.```

I installed python 3.6 using conda instead and it fixed it.

Hopefully this can help someone else :)

Feel free to set to close.

**Comment by tparisotto** [comment]
Getting the same error, solved downgrading numpy from 1.20.1 to 1.19.5
