### ISSUE TITLE
Code is missing

### ISSUE THREAD

**Issue by Zumbalamambo** [ybkscht/EfficientPose#2]

**Comment by ybkscht** [comment]
Hi Zumbalamambo,

thanks for your interest in our project. The code and weights will be released in the next couple days.
I'm sorry for the delay.

**Comment by jtzhangLogan** [comment]
Looking forward to seeing your amazing code!

**Comment by jtzhangLogan** [comment]
When can we expect to see the code? I am looking forward to checking them!

**Comment by cnsystem** [comment]
hope the code could be shared soon.

**Comment by ybkscht** [comment]
Thanks for your patience. I just released the code as well as the pretrained weights.
