### ISSUE TITLE
training on preprocessed YCB-V dataset

### ISSUE THREAD

**Issue by nikonnext** [ybkscht/EfficientPose#20]
Thank you for your work! 
I converted the YCB-V dataset to the same format as linemod_preprocessed. 
I then trained on a new preprocessed YCB-V dataset. The training took place in order to recognize the position of one object. However, after training, the scripts inference.py and inference_webcam.py did not give the expected result. That is, the object and the position of the object are not determined.
Of course, inside the "inference" scripts, I changed the following parameters: path_to_weights, class_to_name (for linemod), get_linemod_camera_matrix, get_linemod_3d_bboxes.

Can you please tell me, maybe I forgot to change some parameter?

**Comment by ybkscht** [comment]
Hi @nikonnext ,

sounds like you have changed the correct parameters. It would be helpful if you could provide some more details.
Do I understand it correctly that you achieved good results in training (ADD(-S), rotation, translation and mAP) and only the inferencing scripts do not give the expected results?
If so, does your trained model usually detect the object but the estimated poses are bad or does the model not detect the object at all?
You can also try to set  `draw_bbox_2d = True` to check if the object was detected (necessary to get a pose).
Does `evaluate.py` give you the expected results?

Sincerely,
Yannick

**Comment by nikonnext** [comment]
Hi @ybkscht , 
I didn't notice right away that I had no predictions. Therefore, the predominant problem comes down to learning. I did preprocessing of the YCB-V dataset (Original synt. Training images) which I took from this link https://bop.felk.cvut.cz/datasets/
The preprocessed dataset is 236 images. I got the best error results at the 5th epoch, however mAP, ADD, ADD-ds are equal to zero.

```
mAP: 0.0000
ADD: 0.0000
ADD-S: 0.0000
5cm_5degree: 0.0000
TranslationErrorMean_in_mm: nan
TranslationErrorStd_in_mm: nan
RotationErrorMean_in_degree: nan
RotationErrorStd_in_degree: nan
2D-Projection: 0.0000
Summed_Translation_Rotation_Error: nan
ADD(-S): 0.0000
AveragePointDistanceMean_in_mm: nan
AveragePointDistanceStd_in_mm: nan
AverageSymmetricPointDistanceMean_in_mm: nan
AverageSymmetricPointDistanceStd_in_mm: nan
MixedAveragePointDistanceMean_in_mm: nan
MixedAveragePointDistanceStd_in_mm: nan

Epoch 00005: ADD did not improve from 0.00000
1790/1790 [==============================] - 564s 315ms/step - loss: 3.5037 - classification_loss: 0.8148 - regression_loss: 0.3623 - transformation_loss: 116.3291
```
Please tell me what this may be related to. After all, the dataset corresponds to Linemod-prerprocessed

**Comment by nikonnext** [comment]
> Hi @ybkscht ,
> I didn't notice right away that I had no predictions. Therefore, the predominant problem comes down to learning. I did preprocessing of the YCB-V dataset (Original synt. Training images) which I took from this link https://bop.felk.cvut.cz/datasets/
> The preprocessed dataset is 236 images. I got the best error results at the 5th epoch, however mAP, ADD, ADD-ds are equal to zero.
> 
> ```
> mAP: 0.0000
> ADD: 0.0000
> ADD-S: 0.0000
> 5cm_5degree: 0.0000
> TranslationErrorMean_in_mm: nan
> TranslationErrorStd_in_mm: nan
> RotationErrorMean_in_degree: nan
> RotationErrorStd_in_degree: nan
> 2D-Projection: 0.0000
> Summed_Translation_Rotation_Error: nan
> ADD(-S): 0.0000
> AveragePointDistanceMean_in_mm: nan
> AveragePointDistanceStd_in_mm: nan
> AverageSymmetricPointDistanceMean_in_mm: nan
> AverageSymmetricPointDistanceStd_in_mm: nan
> MixedAveragePointDistanceMean_in_mm: nan
> MixedAveragePointDistanceStd_in_mm: nan
> 
> Epoch 00005: ADD did not improve from 0.00000
> 1790/1790 [==============================] - 564s 315ms/step - loss: 3.5037 - classification_loss: 0.8148 - regression_loss: 0.3623 - transformation_loss: 116.3291
> ```
> 
> Please tell me what this may be related to. After all, the dataset corresponds to Linemod-prerprocessed
