### ISSUE TITLE
Default batch size

### ISSUE THREAD

**Issue by bainro** [ybkscht/EfficientPose#21]
Hi,

I read the paper where it mentioned that group normalization is used, instead of batch norm, in part due to being able to train well at lower batch sizes. I am trying to speed up training. Is there any reason to keep the batch size as low as 1? Turning up the batch size should speed up training without any major downsides, right?

Also, does this repo currently support multi-gpu training? I looked through the code and it seems that it does not, but would like to make sure.

Regardless, thanks for your time!

**Comment by ybkscht** [comment]
Hi @bainro ,

I do not think that there are any major downsides if you increase the batch size. 
The reason for the low batch size of 1 is that the memory requirements increase very fast if choosing a higher phi and I quickly experienced out of memory issues.
To keep it simple, I have just used the same hyperparameters for all phi.
No, unfortunately multi-gpu training is currently not supported.

Sincerely,
Yannick
