### ISSUE TITLE
Launching EfficientPose in ros

### ISSUE THREAD

**Issue by nikonnext** [ybkscht/EfficientPose#25]
Hi, @ybkscht 

I am trying to run your EfficientPose project in ros and test it with KUKA youbot. Can you give advice on how to implement my idea?

I am using ros melodic. And I ran into the following problem. When you initialize the `inference.py` and `inference_webcam.py` scripts, you use modules that have libraries that work only in python 3. As you know, ros only accepts the syntax of python 2. Please tell me the best way to implement such a project. Should I change the syntax of the whole project to python 2, or is it better to reinstall ros with python 3 support?

**Comment by bainro** [comment]
You can get melodic to work with Python 3, I've done this in the past but it was hacky and brittle. Noetic supports Python 3 without any hacks (if I am remembering incorrectly and it is not actually noetic, it is one of the newer versions, or ROS 2). 

Fixing your ROS to use a python version that isn't 10 years out of data would be easier than making all the packages like tensorflow work for python 2. Good luck!

**Comment by KulikovNA** [comment]
I managed to implement the idea. I used ROS2 in conjunction with libraries `roslibpy` `logging`  `base64`
At the same time, the entire EfficientPose project was in the conda virtual space. Using the proposed libraries is very convenient, like `rosbridge`
The question can be closed, thanks @ybkscht
