### ISSUE TITLE
Loss dropping but ADD still 0

### ISSUE THREAD

**Issue by ame5r** [ybkscht/EfficientPose#29]
Hi, @ybkscht 
Thank you for this amazing work.
I have been trying to run the model on a custom dataset, although the loss is dropping, but the ADD still 0.
Thank you in advance.
(Here is the output after 5 epochs on 1217 images dataset)
`1035 instances of class object with average precision: 0.9975
1035 instances of class object with ADD accuracy: 0.0000
1035 instances of class object with ADD-S-Accuracy: 0.0000
1035 instances of class object with 5cm-5degree-Accuracy: 0.0000
class object with Translation Differences in mm: Mean: 24.2150 and Std: 2.5975
class object with Rotation Differences in degree: Mean: 59.8067 and Std: 21.9196
1035 instances of class object with 2d-projection-Accuracy: 0.0000
1035 instances of class object with ADD(-S)-Accuracy: 0.0000
class object with Transformed Point Distances in mm: Mean: 18.0325 and Std: 3.3026
class object with Transformed Symmetric Point Distances in mm: Mean: 11.4459 and Std: 3.4595
class object with Mixed Transformed Point Distances in mm: Mean: 18.0325 and Std: 3.3026
mAP: 0.9975
ADD: 0.0000
ADD-S: 0.0000
5cm_5degree: 0.0000
TranslationErrorMean_in_mm: 24.2150
TranslationErrorStd_in_mm: 2.5975
RotationErrorMean_in_degree: 59.8067
RotationErrorStd_in_degree: 21.9196
2D-Projection: 0.0000
Summed_Translation_Rotation_Error: 108.5388
ADD(-S): 0.0000
AveragePointDistanceMean_in_mm: 18.0325
AveragePointDistanceStd_in_mm: 3.3026
AverageSymmetricPointDistanceMean_in_mm: 11.4459
AverageSymmetricPointDistanceStd_in_mm: 3.4595
MixedAveragePointDistanceMean_in_mm: 18.0325
MixedAveragePointDistanceStd_in_mm: 3.3026

Epoch 00005: ADD did not improve from 0.00000`

**Comment by enesdoruk** [comment]
i have same issue
