### ISSUE TITLE
Where the occlusion dataset is?

### ISSUE THREAD

**Issue by julingers** [ybkscht/EfficientPose#45]
Hello, I am a new guy. Can anyone tell me where the occlusion dataset is? I downloaded the link shown in README.md, but I only see the Linemod _preprocessed dataset. Is the occlusion dataset included in Linemod_preprocessed dataset?  Sincere thanks！

**Comment by waqarmughal0002** [comment]
have you able to find the dataset as i am thinking about the same?

**Comment by ybkscht** [comment]
Yes you're right, the occlusion dataset is a subset of Linemod. It is included in scene 2 (benchvise).
