### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by sean6585** [ybkscht/EfficientPose#47]
Can anyone help me solve this problem?
I try to train the network using my own dataset, but got an error like this
![Screenshot from 2022-07-01 19-22-17](https://user-images.githubusercontent.com/59359578/176885602-4ceaad78-0dd4-4a61-bfac-cacbd72a856d.png)

My dataset folder look like the picture below.
I followed the file format in Linemod_preprocessed folder.
![Screenshot from 2022-07-01 19-28-04](https://user-images.githubusercontent.com/59359578/176886031-fa2dd56f-e4e9-49ca-bac6-5f02ffe0b886.png)

**Comment by JayLuoShui** [comment]
Hi，how to get gt.yml and info.yml,can you help me？thanks！
