### ISSUE TITLE
set batch size error

### ISSUE THREAD

**Issue by rush9838465** [ybkscht/EfficientPose#5]
Error when I set the batch size to 2。

Note：GPU TITANV(16G)

Traceback (most recent call last):
  File "/home/george/.conda/envs/cuda10/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [2,49104] vs. [2]
	 [[{{node translation/truediv}}]]
	 [[loss/add_1/_4723]]
  (1) Invalid argument: Incompatible shapes: [2,49104] vs. [2]
	 [[{{node translation/truediv}}]]
0 successful operations.
0 derived errors ignored.

**Comment by ybkscht** [comment]
Hi rush,

There was actually a bug when setting the batch size greater than 1 but the latest [commit](https://github.com/ybkscht/EfficientPose/commit/ad5621ac3da2c3a0924fa21772f4f980daecb873) should fix it.
You already closed this issue but I hope this helps you anyway.

Sincerely,
Yannick

**Comment by rush9838465** [comment]
thank you! I will to try



---Original---
