### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by romygt** [ybkscht/EfficientPose#58]
Hi,
I have been exploring various options for integrating pose estimation into my Unity application,  and EfficientPose seems like an excellent fit for my requirements.. As I understand, to deploy EfficientPose in Unity, a pretrained model is required. Therefore, I was wondering if you have a pretrained model available that I can use to integrate EfficientPose into my Unity application.

**Comment by ybkscht** [comment]
Hi @romygt,
You can download the Linemod and Occlusion pretrained weights from [here](https://drive.google.com/drive/folders/1VcBLcIBhuT5MmXfE9NMrFdAk2xzF3mP5?usp=sharing) as stated in the readme. But please note that if you want to use EfficientPose for different objects, than you have to train it using a dataset that contains these objects.
