### ISSUE TITLE
Evaluating only every 10 epochs

### ISSUE THREAD

**Issue by MaxWaterhout** [ybkscht/EfficientPose#59]
Hello! First of, thanks for the great model. I only have a question. In the paper it states that you only evaluate every 10 epochs but in the code it evaluates after every epoch. Is there something I can change in the code for it to do that? I already tried some myself but I couldnt get it to work. This could speed up my training severly! Thanks in advance!

**Comment by ybkscht** [comment]
Hi @maxiew123,
Evaluating only every 10 epochs is set indirectly via the --steps argument in train.py
`parser.add_argument('--steps', help = 'Number of steps per epoch.', type = int, default = int(179 * 10))`
The Linemod dataset contains only about 179 training images, so we just hardcoded the number of steps per epoch times 10 to reduce the validation computation time overhead.
You can adjust the value according to your dataset size and needs.

**Comment by MaxWaterhout** [comment]
Thanks for the quick reply! now I understand the logic behind it.
