### ISSUE TITLE
Question about the dataset process

### ISSUE THREAD

**Issue by sunnyx33** [ybkscht/EfficientPose#61]
Hello, thanks for your work. 
One of the features of your method is that it can predict the poses of multiple different objects in one inference. To achieve multi-object detection, you processed the class 2 (benchvise) data in the linemod dataset, which originally only annotated the pose and bounding box of class 2, and your class 2 data annotation included the pose and bounding box of all objects that appeared in the image. I wonder how did you achieve this effect? Can I do the same for other classes of data?
Thanks for your help!

**Comment by ybkscht** [comment]
Hi @sunyx33,
this is actually the Occlusion dataset. It is basically a subset of Linemod (scene 2) and includes GT annotations of all visible objects in this scene.

**Comment by sunnyx33** [comment]
got it. Thanks!
