### ISSUE TITLE
models_info.yml data

### ISSUE THREAD

**Issue by geoffhorowitz** [ybkscht/EfficientPose#9]
Hi Yannick,

Quick questions for you regarding the data in Linemod_preprocessed/models/models_info.yml:
1) I assume the diameter values are in mm?  can you confirm?
2) What exactly are the min_{x,y,z} and size_{x,y,z} values relating to?  Is this a value from the .ply file? I assume its not related to the ground truth data since there's only one per item.  Also, any idea what the units are here?

I know you took this dataset from densefusion[https://github.com/j96w/DenseFusion](url) - I've been digging around there and haven't been able to find this. If I missed it, please do point me.

Thanks!

**Comment by ybkscht** [comment]
Hi geoffhorowitz,

Yes the dataset unit is mm. The min_{x,y,z} and size_{x,y,z} values represent the 3D bounding box of the object, also in mm. The 3D bboxes are used for visualization.
They are transformed with the GT and predicted poses and then projected onto the image.

In the README under "Datsets", in the second point there is a link to the [preprocessed LineMOD dataset](https://drive.google.com/drive/folders/19ivHpaKm9dOrr12fzC8IDFczWRPFxho7)

**Comment by geoffhorowitz** [comment]
Thank you!

Gonna leave this issue open as a reference for anyone else who wants it, but feel free to close if you prefer to clear issues....
